/**
 * The documentation as paper rolls for the reader. Plain typewriter lines; the reader wraps
 * nothing, so every line is kept under 42 characters.
 */
export interface Roll {
  code: string;
  title: string;
  lines: string[];
}

const RULE = "- - - - - - - - - - - - - - - - - - - - -";
const MARK = ["        |  |  |", "       -+--+--+-", "        |  |  |", "       -+--+--+-", "        |  |  |", "       ---------"];

export const ROLLS: Roll[] = [
  {
    code: "01",
    title: "Getting started",
    lines: [
      ...MARK,
      "",
      "SHEAF  .  DOCUMENTATION  .  ROLL 01",
      "GETTING STARTED",
      RULE,
      "",
      "Create a workspace (you become its",
      "Owner) or sign in to the seeded demo",
      "organisation.",
      "",
      "In Settings, confirm the asset and",
      "network. In real mode, set the",
      "treasury wallet address.",
      "",
      "Open Batches > New batch, give it a",
      "name and an optional deadline.",
      "",
      "Upload a CSV, fix any flagged rows,",
      "prepare routes, then hand it to an",
      "approver.",
      "",
      "      upload ---> validate",
      "                     |",
      "                     v",
      "   reconcile <--- execute <--- approve",
      "",
      RULE,
      "Seeded demo accounts",
      "",
      "  owner@northwind.example",
      "  finance@northwind.example",
      "  approver@northwind.example",
      "  viewer@northwind.example",
      "",
      "  password  sheaf-demo-2026",
      "",
      "This instance runs in the mode shown",
      "on the printer's start page. Developer",
      "setup: docs/development.md in the",
      "repository.",
      "",
      "                    [ next roll: CSV ]",
    ],
  },
  {
    code: "02",
    title: "CSV format",
    lines: [
      ...MARK,
      "",
      "SHEAF  .  DOCUMENTATION  .  ROLL 02",
      "CSV FORMAT",
      RULE,
      "",
      "Required columns:",
      "",
      "  name . address . amount",
      "",
      "Optional:",
      "",
      "  asset . reference",
      "",
      "Header aliases are recognised:",
      "  Contractor name, Wallet address,",
      "  Payment amount, Invoice.",
      "",
      "Delimiters: comma, semicolon or tab.",
      "Limits: 5 MB, 10,000 rows.",
      "",
      "  +----------+------------+---------+",
      "  | name     | address    | amount  |",
      "  +----------+------------+---------+",
      "  | Ana R.   | 0x8f3..c21e| 1250.00 |",
      "  | Studio K | 0x91d..4b7a|  480.00 |",
      "  | M. Okafor| 0x2c8..9f03|    0.35 |",
      "  +----------+------------+---------+",
      "",
      "Amounts are decimal strings. More",
      "decimals than the asset supports is",
      "an error, never rounded.",
      "",
      "Mixed-case addresses must pass the",
      "EIP-55 checksum. All-lowercase",
      "addresses are accepted.",
      "",
      "The same wallet twice in one batch is",
      "an error on the second row (merge or",
      "remove).",
      "",
      "Invalid rows are kept and shown with",
      "their errors; they can be corrected",
      "or removed in place.",
      "",
      "Template: GET /api/template",
    ],
  },
  {
    code: "03",
    title: "Batch workflow",
    lines: [
      ...MARK,
      "",
      "SHEAF  .  DOCUMENTATION  .  ROLL 03",
      "BATCH WORKFLOW",
      RULE,
      "",
      "Statuses move strictly:",
      "",
      "  Draft",
      "    |",
      "  Validated",
      "    |",
      "  Routes prepared",
      "    |",
      "  Approved",
      "    |",
      "  Funded",
      "    |",
      "  Executing",
      "    |",
      "  Completed / Partially failed / Failed",
      "",
      "A batch can be cancelled until it is",
      "funded.",
      "",
      "Uploading a CSV never executes",
      "anything.",
      "",
      RULE,
      "ROLES AND APPROVALS",
      "",
      "  Owner          everything, incl.",
      "                 settings and members",
      "  Finance admin  create, edit, prepare,",
      "                 fund, execute, retry,",
      "                 reconcile, export.",
      "                 Cannot approve.",
      "  Approver       approve or revoke,",
      "                 view full addresses,",
      "                 export.",
      "  Viewer         read-only, redacted",
      "                 addresses, no exports.",
      "",
      "With four-eyes enabled (default), the",
      "person who last changed the recipient",
      "set cannot approve it. Approvals",
      "record the approver, the total and a",
      "hash of the recipient set; any edit",
      "invalidates them.",
    ],
  },
  {
    code: "04",
    title: "Demo vs real mode",
    lines: [
      ...MARK,
      "",
      "SHEAF  .  DOCUMENTATION  .  ROLL 04",
      "DEMO VS REAL MODE",
      RULE,
      "",
      "DEMO uses a deterministic mock",
      "provider: no network calls, no funds.",
      "Every route, funding record, attempt",
      "and export row is flagged simulated.",
      "",
      "Scenario triggers for testers:",
      "",
      "  address ends in ...dead",
      "    fails permanently",
      "  address ends in ...beef",
      "    fails once, succeeds on retry",
      "  address ends in ...0000",
      "    gets no route",
      "  amount exactly 0.13",
      "    is refunded",
      "",
      RULE,
      "",
      "REAL quotes routes from Relay's public",
      "API and requires the configured",
      "treasury wallet to sign each route",
      "step in the browser. The server never",
      "holds a private key.",
      "",
      "Real mode has been verified for",
      "quoting and status polling; no",
      "on-chain execution was performed",
      "during development.",
      "",
      "Modes never switch silently: each",
      "batch records the mode it was created",
      "in and refuses to execute under a",
      "different one.",
    ],
  },
  {
    code: "05",
    title: "Execution and retries",
    lines: [
      ...MARK,
      "",
      "SHEAF  .  DOCUMENTATION  .  ROLL 05",
      "EXECUTION AND RETRIES",
      RULE,
      "",
      "One job per payment, claimed with a",
      "conditional update so two workers",
      "never run the same job.",
      "",
      "Idempotency key:",
      "",
      "  exec:batch:recipient:attempt",
      "",
      "Re-running a crashed job cannot send",
      "twice.",
      "",
      "A payment is never retried while its",
      "last attempt is pending, submitted or",
      "unknown. Unknown status after repeated",
      "failed checks stops polling and asks",
      "for manual review instead of",
      "resending.",
      "",
      "Retries are explicit, limited",
      "(default 3) and only offered for",
      "provider-classified transient",
      "failures.",
      "",
      "Optional spacing (jitter) between",
      "submissions is bounded to 30 minutes",
      "and never past the batch deadline.",
      "",
      "  attempt 1 ---x  transient",
      "  attempt 2 ---x  transient",
      "  attempt 3 ---o  confirmed 0x4e19..",
      "",
      RULE,
      "RECONCILIATION AND EXPORTS",
      "",
      "Successful fills are marked Matched",
      "automatically with their reference",
      "and fee estimate; failures and",
      "refunds become Exceptions. Finance",
      "can override any state with a note.",
      "",
      "The CSV export contains batch,",
      "recipient, amount, network,",
      "references, statuses, attempts, fees,",
      "timestamps and a simulated column.",
    ],
  },
  {
    code: "06",
    title: "Known limitations",
    lines: [
      ...MARK,
      "",
      "SHEAF  .  DOCUMENTATION  .  ROLL 06",
      "KNOWN LIMITATIONS",
      RULE,
      "",
      "Encryption at rest uses one",
      "server-side key (no per-organisation",
      "KMS keys); the audit table is",
      "append-only but not externally",
      "anchored.",
      "",
      "EVM addresses only.",
      "",
      "Real mode untested end-to-end",
      "on-chain; use Base Sepolia first.",
      "",
      "Public Relay rate limit (50 quotes",
      "per minute) bounds route preparation",
      "speed without an API key.",
      "",
      "The in-process worker suits a single",
      "server; multi-instance deployments",
      "should trigger POST /api/worker/run",
      "from a scheduler instead.",
      "",
      "Same-chain, same-token routes provide",
      "no external privacy.",
      "",
      RULE,
      "",
      "            end of documentation",
      "            turn to roll 01",
    ],
  },
];
