/**
 * The documentation as paper rolls for the reader. Plain typewriter lines; the reader wraps
 * nothing, so every line is kept under 42 characters.
 */
export interface Roll {
  code: string;
  title: string;
  lines: string[];
}

const RULE = "- - - - - - - - - - - - - - - - - - - - -";
const MARK = ["        |  |  |", "       -+--+--+-", "        |  |  |", "       -+--+--+-", "        |  |  |", "       ---------"];

export const ROLLS: Roll[] = [
  {
    code: "01",
    title: "Getting started",
    lines: [
      ...MARK,
      "",
      "SHEAF  .  DOCUMENTATION  .  ROLL 01",
      "GETTING STARTED",
      RULE,
      "",
      "Sheaf is the private execution desk",
      "for Robinhood Chain (chain id 4663).",
      "A sheaf is one controlled operation",
      "made of legs, executed from one desk.",
      "Settlement asset: USDG.",
      "",
      "Sign in with a wallet or with the",
      "seeded demo credentials. A first",
      "wallet sign-in creates a desk owned",
      "by that wallet.",
      "",
      "Open the desk > New operation, pick",
      "a kind, add legs, validate, prepare",
      "routes, then hand it to an approver.",
      "",
      "      legs ----> validate",
      "                     |",
      "                     v",
      "                  route",
      "                     |",
      "                     v",
      "   reconcile <--- execute <--- approve",
      "                     ^",
      "                   fund",
      "",
      RULE,
      "Seeded demo accounts",
      "",
      "  owner@halden.example",
      "  desk@halden.example      (operator)",
      "  approver@halden.example",
      "  viewer@halden.example",
      "",
      "  password  sheaf-demo-2026",
      "",
      "The demo desk simulates everything",
      "and labels every record simulated.",
      "Developer setup: docs/development.md",
      "in the repository.",
      "",
      "             [ next roll: operations ]",
    ],
  },
  {
    code: "02",
    title: "Operation kinds",
    lines: [
      ...MARK,
      "",
      "SHEAF  .  DOCUMENTATION  .  ROLL 02",
      "OPERATION KINDS",
      RULE,
      "",
      "CLAIM  .  Private allocation claim",
      "  contract PrivateClaim",
      "  A launch publishes a Merkle root of",
      "  allocations. The eligible wallet",
      "  proves eligibility and designates a",
      "  fresh recipient by EIP-712",
      "  signature. Tokens go straight to",
      "  the recipient. One claim per",
      "  account. After the window closes,",
      "  the owner sweeps what is unclaimed.",
      "",
      "ACCUMULATE  .  Stealth accumulation",
      "  contract StealthDesk",
      "  The treasury deposits USDG and",
      "  commits a plan: a Merkle root over",
      "  legs (recipient, token, amount,",
      "  notBefore, salt). An operator",
      "  reveals and executes one leg at a",
      "  time after its notBefore.",
      "  Unexecuted legs and the total stay",
      "  hidden; executed payouts are",
      "  public. Cancel and withdraw any",
      "  time.",
      "",
      "OTC  .  Private OTC block",
      "  contract OtcEscrow",
      "  Maker deposits asset A, names a",
      "  counterparty (or anyone), wants",
      "  asset B, sets expiry. Taker fills",
      "  atomically in one transaction.",
      "  Never touches a pool or order",
      "  book. Each side can receive into a",
      "  fresh address. Expired or",
      "  unfilled: maker refunds.",
      "",
      "TREASURY  .  Delegated treasury",
      "  contract DelegatedTreasury",
      "  Owner funds. Operator proposes",
      "  (token, to, amount). An approver",
      "  who is not the proposer approves.",
      "  Operator executes. Daily spend cap",
      "  per token. Owner withdraws any",
      "  time. Four-eyes enforced on-chain.",
      "",
      RULE,
      "",
      "Robinhood Stock Tokens have transfer",
      "restrictions: compliance checks on",
      "sender and receiver. A fresh,",
      "unverified address cannot hold them.",
      "Validation flags such legs before",
      "anything is signed.",
    ],
  },
  {
    code: "03",
    title: "Leg CSV format",
    lines: [
      ...MARK,
      "",
      "SHEAF  .  DOCUMENTATION  .  ROLL 03",
      "LEG CSV FORMAT",
      RULE,
      "",
      "Columns, in this order:",
      "",
      "  label . address . asset . amount",
      "  not-before . memo",
      "",
      "Required: address, asset, amount.",
      "Optional: label, not-before, memo.",
      "",
      "Delimiters: comma, semicolon or tab.",
      "Paste the rows or drop the file.",
      "",
      "  +--------+------------+------+-------+",
      "  | label  | address    | asset| amount|",
      "  +--------+------------+------+-------+",
      "  | leg-01 | 0x8f3..c21e| USDG | 25000 |",
      "  | leg-02 | 0x91d..4b7a| USDG | 25000 |",
      "  | leg-03 | 0x2c8..9f03| USDG | 20000 |",
      "  +--------+------------+------+-------+",
      "",
      "Amounts are decimal strings. More",
      "decimals than the asset supports is",
      "an error, never rounded.",
      "",
      "not-before is an ISO timestamp. The",
      "leg is not executed before it. Legs",
      "in a plan must be in not-before",
      "order.",
      "",
      "Mixed-case addresses must pass the",
      "EIP-55 checksum. All-lowercase",
      "addresses are accepted.",
      "",
      "The same address twice in one sheaf",
      "is a warning, not an error: an",
      "accumulation may pay one recipient",
      "in several legs.",
      "",
      "Invalid legs are kept and shown with",
      "their errors; correct or remove them",
      "in place.",
      "",
      "Template: GET /api/template",
    ],
  },
  {
    code: "04",
    title: "Workflow and roles",
    lines: [
      ...MARK,
      "",
      "SHEAF  .  DOCUMENTATION  .  ROLL 04",
      "WORKFLOW AND ROLES",
      RULE,
      "",
      "Statuses move strictly:",
      "",
      "  Draft",
      "    |",
      "  Validated",
      "    |",
      "  Routes prepared",
      "    |",
      "  Approved",
      "    |",
      "  Funded",
      "    |",
      "  Executing",
      "    |",
      "  Completed / Partially failed / Failed",
      "",
      "A sheaf can be cancelled until it is",
      "funded. After funding, cancelling",
      "calls the contract's cancel and",
      "withdraws what remains.",
      "",
      "Adding legs never executes anything.",
      "",
      RULE,
      "ROLES",
      "",
      "  Owner          everything, incl.",
      "                 settings, members,",
      "                 funding, withdrawal",
      "  Desk operator  create, edit legs,",
      "                 validate, route,",
      "                 execute, retry,",
      "                 reconcile, export.",
      "                 Cannot approve.",
      "  Approver       approve or revoke,",
      "                 view full addresses,",
      "                 export.",
      "  Viewer         read-only, redacted",
      "                 addresses, no exports.",
      "",
      "Four-eyes: the person who last",
      "changed the leg set cannot approve",
      "it. Approvals record the approver,",
      "the total and a hash of the leg set;",
      "any edit invalidates them.",
      "",
      "For TREASURY operations the same",
      "rule is enforced a second time by",
      "DelegatedTreasury on-chain.",
    ],
  },
  {
    code: "05",
    title: "Demo vs real mode",
    lines: [
      ...MARK,
      "",
      "SHEAF  .  DOCUMENTATION  .  ROLL 05",
      "DEMO VS REAL MODE",
      RULE,
      "",
      "DEMO uses a deterministic mock",
      "provider and a simulated chain: no",
      "network calls, no funds. Every",
      "route, funding record, attempt and",
      "export row is flagged simulated.",
      "",
      "Scenario triggers for testers:",
      "",
      "  address ends in ...dead",
      "    fails permanently",
      "  address ends in ...beef",
      "    fails once, succeeds on retry",
      "  address ends in ...0000",
      "    gets no route",
      "  asset is a Stock Token and the",
      "  address is not verified",
      "    rejected at validation",
      "",
      RULE,
      "",
      "REAL signs with the connected wallet",
      "in the browser: contract calls on",
      "Robinhood Chain and, for legs that",
      "start on another chain, route steps",
      "quoted from Relay's public API. The",
      "server never holds a private key.",
      "",
      "Real mode has been verified for",
      "quoting, contract simulation and",
      "status polling; no mainnet execution",
      "was performed during development.",
      "",
      "Modes never switch silently: each",
      "sheaf records the mode it was created",
      "in and refuses to execute under a",
      "different one.",
    ],
  },
  {
    code: "06",
    title: "Contracts",
    lines: [
      ...MARK,
      "",
      "SHEAF  .  DOCUMENTATION  .  ROLL 06",
      "CONTRACTS",
      RULE,
      "",
      "Four contracts in contracts/. Each",
      "is small, single-purpose and owned",
      "by the desk that deploys it.",
      "",
      "PrivateClaim",
      "  roles   owner, claimant",
      "  events  Claimed(account, recipient,",
      "          amount), Swept(amount)",
      "  honest  the Claimed event links",
      "          account to recipient on",
      "          chain; the recipient is not",
      "          the account, nothing more.",
      "",
      "StealthDesk",
      "  roles   owner, operator",
      "  events  PlanCommitted(root),",
      "          LegExecuted(recipient,",
      "          token, amount),",
      "          Cancelled()",
      "  honest  each executed leg is a",
      "          public transfer from the",
      "          desk; the root hides only",
      "          what has not run yet.",
      "",
      "OtcEscrow",
      "  roles   maker, taker",
      "  events  Offered(id), Filled(id),",
      "          Refunded(id)",
      "  honest  both legs of the fill are",
      "          visible in one transaction;",
      "          only the receiving addresses",
      "          are chosen by each side.",
      "",
      "DelegatedTreasury",
      "  roles   owner, operator, approver",
      "  events  Proposed(id), Approved(id),",
      "          Executed(id), Withdrawn()",
      "  honest  every step is public; the",
      "          contract, not the app, is",
      "          what refuses a self-approval.",
      "",
      RULE,
      "",
      "In every operation the desk contract",
      "address is the on-chain sender. The",
      "owning wallet funds the contract; that",
      "funding transfer is public too.",
    ],
  },
  {
    code: "07",
    title: "Execution and reconciliation",
    lines: [
      ...MARK,
      "",
      "SHEAF  .  DOCUMENTATION  .  ROLL 07",
      "EXECUTION AND RECONCILIATION",
      RULE,
      "",
      "One job per leg, claimed with a",
      "conditional update so two workers",
      "never run the same job.",
      "",
      "Idempotency key:",
      "",
      "  exec:sheaf:leg:attempt",
      "",
      "Re-running a crashed job cannot send",
      "twice.",
      "",
      "A leg is never retried while its last",
      "attempt is pending, submitted or",
      "unknown. Unknown status after",
      "repeated failed checks stops polling",
      "and asks for manual review instead",
      "of resending.",
      "",
      "A leg is never submitted before its",
      "not-before. Retries are explicit,",
      "limited (default 3) and only offered",
      "for transient failures.",
      "",
      "  attempt 1 ---x  transient",
      "  attempt 2 ---x  transient",
      "  attempt 3 ---o  executed 0x4e19..",
      "",
      RULE,
      "RECONCILIATION AND EXPORTS",
      "",
      "Executed legs are marked Matched",
      "automatically with their hash and",
      "fee; failures and refunds become",
      "Exceptions. The operator can",
      "override any state with a note.",
      "",
      "The CSV export contains sheaf, kind,",
      "contract, leg, recipient, asset,",
      "amount, not-before, hash, status,",
      "attempts, fees, timestamps and a",
      "simulated column.",
      "",
      "The audit trail is append-only:",
      "every state change, approval,",
      "download and export is an event.",
    ],
  },
  {
    code: "08",
    title: "Known limitations",
    lines: [
      ...MARK,
      "",
      "SHEAF  .  DOCUMENTATION  .  ROLL 08",
      "KNOWN LIMITATIONS",
      RULE,
      "",
      "Stock Tokens: transfer restrictions",
      "apply to sender and receiver. A",
      "fresh, unverified address cannot",
      "receive them, so CLAIM and OTC legs",
      "in Stock Tokens need a verified",
      "recipient. Sheaf cannot verify an",
      "address for you.",
      "",
      "Correlation: amounts, timing and the",
      "desk contract are public. An",
      "observer can correlate a funding",
      "transfer with later payouts. Sheaf",
      "hides the owner as destination; it",
      "does not hide the operation.",
      "",
      "Claims emit an on-chain event that",
      "links the eligible account to its",
      "recipient.",
      "",
      "No gasless claims: the claiming",
      "wallet pays gas on Robinhood Chain.",
      "",
      "No prize or reward settlement; the",
      "four operations are the whole scope.",
      "",
      "Real mode not executed on mainnet",
      "during development; use a testnet",
      "first.",
      "",
      "Encryption at rest uses one",
      "server-side key; the audit table is",
      "append-only but not externally",
      "anchored.",
      "",
      "EVM addresses only. Public Relay",
      "rate limit (50 quotes per minute)",
      "bounds cross-chain route preparation",
      "without an API key.",
      "",
      "The in-process worker suits a single",
      "server; multi-instance deployments",
      "should trigger POST /api/worker/run",
      "from a scheduler instead.",
      "",
      RULE,
      "",
      "            end of documentation",
      "            turn to roll 01",
    ],
  },
];
